---
aws_profile:
  - aws_account_id:      <aws_account_id>
  - aws_region:          ap-southeast-2
  - aws_profile:         default


aws_ec2_profile:
  - instance_type:       t2.micro
  - masterkey_name:      lab_masterkey
  - masterkey_path:      /root/adlab/test-lab/lab_masterkey.pem


network:
  - network_cidr:        172.16.10.0/24


firewall_rules:
  - rule_1:
    - name:              allow_all_to_internal
    - type:              ingress
    - port:              0
    - protocol:          "-1"
    - cidr_blocks:       "172.16.10.0/24"
  - rule_2:
    - name:              open_ssh
    - type:              ingress
    - port:              22
    - protocol:          tcp
    - cidr_blocks:       "0.0.0.0/0"
  - rule_3:
    - name:              open_rdp
    - type:              ingress
    - port:              3389
    - protocol:          tcp
    - cidr_blocks:       "0.0.0.0/0"
  - rule_4:
    - name:              open_ansible
    - type:              ingress
    - port:              5986
    - protocol:          tcp
    - cidr_blocks:       "0.0.0.0/0"
  - rule_5:
    - name:              open_vpn
    - type:              ingress
    - port:              1194
    - protocol:          udp
    - cidr_blocks:       "0.0.0.0/0"
  - rule_6:
    - name:              allow_all_to_Internet
    - type:              egress
    - port:              0
    - protocol:          "-1"
    - cidr_blocks:       "0.0.0.0/0"
  - rule_7:
    - name:              open_http
    - type:              ingress
    - port:              80
    - protocol:          tcp
    - cidr_blocks:       "0.0.0.0/0"
  - rule_8:
    - name:              open_https
    - type:              ingress
    - port:              443
    - protocol:          tcp
    - cidr_blocks:       "0.0.0.0/0"


instances:
  - instance01:
    - os_type:           windows
    - ami:               ami-097e5cc4436eb9115
    - private_ip:        172.16.10.100
    - hostname:          avtest
#  - instance03:
#    - os_type:           linux
#    - ami:               ami-0f39d06d145e9bb63
#    - private_ip:        172.16.10.10
#    - hostname:          vpnserver



ansible_inventory:
  - windows:             instance01
#  - linux:               instance01
  - avtest:              instance01
#  - vpnserver:           instance01

ansible_vars_all:
  - ansible_user:                                administrator
  - ansible_port:                                5986
  - ansible_connection:                          winrm
  - ansible_winrm_server_cert_validation:        ignore
